modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
issueTrackerURL = "${githubUrl}/issues?q=is%3Aissue"
license = "MIT"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
displayURL = "${githubUrl}"
updateJSONURL = "${githubUrl}/blob/main/updates.json"
authors = "${modAuthor}"
description = '''
${modDescription}
'''

[[dependencies.tinkersepicfight]]
	modId = "forge"
	mandatory = true
	versionRange = "${forgeVersionRange}"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.tinkersepicfight]]
	modId = "minecraft"
	mandatory = true
	versionRange = "${minecraftVersionRange}"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.tinkersepicfight]]
	modId = "tconstruct"
	mandatory = true
	versionRange = "${tconstructVersionRange}"
	ordering = "AFTER"
	side = "BOTH"
[[dependencies.tinkersepicfight]]
	modId = "epicfight"
	mandatory = true
	versionRange = "${epicfightVersionRange}"
	ordering = "AFTER"
	side = "BOTH"