modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
license = "MIT"
issueTrackerURL = "${githubUrl}/issues?q=is%3Aissue"

[[mods]]
displayName = "${modName}"
version = "${file.jarVersion}"
modId = "${modId}"
authors = "${modAuthor}"
displayURL = "${githubUrl}"
updateJSONURL = "${githubRaw}/updates.json"
description = '''
${modDescription}
'''

[[dependencies.tinkersepicfight]]
	modId = "forge"
	mandatory = true
	versionRange = "${forgeVersionRange}"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.tinkersepicfight]]
	modId = "minecraft"
	mandatory = true
	versionRange = "${minecraftVersionRange}"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.tinkersepicfight]]
	modId = "tconstruct"
	mandatory = true
	versionRange = "${tconstructVersionRange}"
	ordering = "AFTER"
	side = "BOTH"
[[dependencies.tinkersepicfight]]
	modId = "epicfight"
	mandatory = true
	versionRange = "${epicfightVersionRange}"
	ordering = "AFTER"
	side = "BOTH"